#开发环境配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.24.16:3306/huii_admin?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      pool-prepared-statements: true
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
  redis:
    host: 192.168.24.16
    port: 6379
    database: 0
    password:
    connect-timeout: 100000
  rabbitmq:
    host:
  mail:
    port: 465
    protocol: smtps
    host: smtp.163.com
    username:
    password:
    default-encoding: UTF-8


logging:
  level:
    root: info
    com.huii.admin: debug

oss:
  config:
    end-point:
    bucket-name:
    key-id:
    key-secret:
    open: false

