server:
  port: 8082

spring:
  application:
    name: admin
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant-path-matcher


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  single: 24